export const skills = {
    mining: {
        name: "Mining",
        frenchName: "Minage",
        actions: {
            Sculk: { xp: 4, image: "" },
            Sculk_Vein: { xp: 3, image: "" },
            Sculk_Sensor: { xp: 6, image: "" },
            Sculk_Catalyst: { xp: 10, image: "" },
            Sculk_Shrieker: { xp: 12, image: "" },
            Reinforced_Deepslate: { xp: 40, image: "" },
            Tuff: { xp: 10, image: "" },
            Copper_Ore: { xp: 200, image: "" },
            Deepslate_Copper_Ore: { xp: 200, image: "" },
            Deepslate: { xp: 40, image: "" },
            Cobbled_Deepslate: { xp: 40, image: "" },
            Calcite: { xp: 100, image: "" },
            Smooth_Basalt: { xp: 50, image: "" },
            Amethyst_Block: { xp: 100, image: "" },
            Budding_Amethyst: { xp: 100, image: "" },
            Small_Amethyst_Bud: { xp: 0, image: "" },
            Medium_Amethyst_Bud: { xp: 0, image: "" },
            Large_Amethyst_Bud: { xp: 30, image: "" },
            Amethyst_Cluster: { xp: 60, image: "" },
            Bone_Block: { xp: 50, image: "" },
            Crying_Obsidian: { xp: 100, image: "" },
            Chain: { xp: 10, image: "" },
            Blackstone: { xp: 50, image: "" },
            Warped_Nylium: { xp: 5, image: "" },
            Crimson_Nylium: { xp: 5, image: "" },
            Ancient_Debris: { xp: 5000, image: "" },
            Magma_Block: { xp: 30, image: "" },
            Basalt: { xp: 40, image: "" },
            Tube_Coral_Block: { xp: 40, image: "" },
            Brain_Coral_Block: { xp: 40, image: "" },
            Bubble_Coral_Block: { xp: 40, image: "" },
            Fire_Coral_Block: { xp: 40, image: "" },
            Horn_Coral_Block: { xp: 40, image: "" },
            Coal_Ore: { xp: 100, image: "" },
            Deepslate_Coal_Ore: { xp: 200, image: "" },
            Diamond_Ore: { xp: 750, image: "" },
            Deepslate_Diamond_Ore: { xp: 750, image: "" },
            Emerald_Ore: { xp: 650, image: "" },
            Deepslate_Emerald_Ore: { xp: 650, image: "" },
            End_Stone_Bricks: { xp: 50, image: "" },
            Chiseled_Nether_Bricks: { xp: 50, image: "" },
            Cracked_Nether_Bricks: { xp: 50, image: "" },
            Nether_Bricks: { xp: 50, image: "" },
            Red_Nether_Bricks: { xp: 50, image: "" },
            End_Stone: { xp: 15, image: "" },
            Glowstone: { xp: 15, image: "" },
            Gold_Ore: { xp: 350, image: "" },
            Deepslate_Gold_Ore: { xp: 350, image: "" },
            Nether_Gold_Ore: { xp: 150, image: "" },
            Gilded_Blackstone: { xp: 50, image: "" },
            Terracotta: { xp: 30, image: "" },
            Iron_Ore: { xp: 250, image: "" },
            Deepslate_Iron_Ore: { xp: 250, image: "" },
            Lapis_Ore: { xp: 400, image: "" },
            Deepslate_Lapis_Ore: { xp: 400, image: "" },
            Mossy_Cobblestone: { xp: 30, image: "" },
            Netherrack: { xp: 15, image: "" },
            Obsidian: { xp: 150, image: "" },
            Packed_Ice: { xp: 15, image: "" },
            Blue_Ice: { xp: 15, image: "" },
            Nether_Quartz_Ore: { xp: 300, image: "" },
            Redstone_Ore: { xp: 400, image: "" },
            Deepslate_Redstone_Ore: { xp: 400, image: "" },
            Sandstone: { xp: 30, image: "" },
            Black_Terracotta: { xp: 50, image: "" },
            Blue_Terracotta: { xp: 50, image: "" },
            Brown_Terracotta: { xp: 50, image: "" },
            Cyan_Terracotta: { xp: 50, image: "" },
            Gray_Terracotta: { xp: 50, image: "" },
            Green_Terracotta: { xp: 50, image: "" },
            Light_Blue_Terracotta: { xp: 50, image: "" },
            Light_Gray_Terracotta: { xp: 50, image: "" },
            Lime_Terracotta: { xp: 50, image: "" },
            Magenta_Terracotta: { xp: 50, image: "" },
            Orange_Terracotta: { xp: 50, image: "" },
            Pink_Terracotta: { xp: 50, image: "" },
            Purple_Terracotta: { xp: 50, image: "" },
            Red_Terracotta: { xp: 50, image: "" },
            White_Terracotta: { xp: 50, image: "" },
            Yellow_Terracotta: { xp: 50, image: "" },
            Stone: { xp: 15, image: "" },
            Granite: { xp: 15, image: "" },
            Andesite: { xp: 15, image: "" },
            Diorite: { xp: 15, image: "" },
            Stone_Bricks: { xp: 50, image: "" },
            Cracked_Stone_Bricks: { xp: 50, image: "" },
            Mossy_Stone_Bricks: { xp: 50, image: "" },
            Chiseled_Stone_Bricks: { xp: 50, image: "" },
            Red_Sandstone: { xp: 100, image: "" },
            Prismarine: { xp: 70, image: "" },
            Prismarine_Bricks: { xp: 70, image: "" },
            Dark_Prismarine: { xp: 70, image: "" },
            Sea_Lantern: { xp: 70, image: "" },
            Purpur_Block: { xp: 70, image: "" },
            Purpur_Pillar: { xp: 70, image: "" },
            Purpur_Slab: { xp: 70, image: "" },
            Purpur_Stairs: { xp: 70, image: "" },
            Packed_Mud: { xp: 70, image: "" },
            Mud_Bricks: { xp: 40, image: "" },
            Dripstone_Block: { xp: 35, image: "" },
        },
    },
    woodcutting: {
        name: "Woodcutting",
        frenchName: "Bûcheronnage",
        actions: {
            Crimson_Hyphae: { xp: 50, image: "" },
            Stripped_Crimson_Hyphae: { xp: 50, image: "" },
            Warped_Hyphae: { xp: 50, image: "" },
            Stripped_Warped_Hyphae: { xp: 50, image: "" },
            Nether_Wart_Block: { xp: 1, image: "" },
            Warped_Wart_Block: { xp: 1, image: "" },
            Shroomlight: { xp: 90, image: "" },
            Crimson_Stem: { xp: 35, image: "" },
            Warped_Stem: { xp: 35, image: "" },
            Oak_Log: { xp: 70, image: "" },
            Cherry_Log: { xp: 105, image: "" },
            Spruce_Log: { xp: 80, image: "" },
            Birch_Log: { xp: 90, image: "" },
            Jungle_Log: { xp: 100, image: "" },
            Acacia_Log: { xp: 90, image: "" },
            Dark_Oak_Log: { xp: 90, image: "" },
            Pale_Oak_Log: { xp: 90, image: "" },
            Stripped_Oak_Log: { xp: 70, image: "" },
            Stripped_Cherry_Log: { xp: 90, image: "" },
            Stripped_Spruce_Log: { xp: 80, image: "" },
            Stripped_Birch_Log: { xp: 90, image: "" },
            Stripped_Jungle_Log: { xp: 90, image: "" },
            Stripped_Acacia_Log: { xp: 90, image: "" },
            Stripped_Dark_Oak_Log: { xp: 90, image: "" },
            Stripped_Pale_Oak_Log: { xp: 90, image: "" },
            Stripped_Oak_Wood: { xp: 70, image: "" },
            Stripped_Cherry_Wood: { xp: 70, image: "" },
            Stripped_Spruce_Wood: { xp: 80, image: "" },
            Stripped_Birch_Wood: { xp: 90, image: "" },
            Stripped_Jungle_Wood: { xp: 90, image: "" },
            Stripped_Acacia_Wood: { xp: 90, image: "" },
            Stripped_Dark_Oak_Wood: { xp: 90, image: "" },
            Stripped_Pale_Oak_Wood: { xp: 90, image: "" },
            Stripped_Mangrove_Log: { xp: 90, image: "" },
            Stripped_Crimson_Stem: { xp: 50, image: "" },
            Stripped_Warped_Stem: { xp: 50, image: "" },
            Oak_Wood: { xp: 70, image: "" },
            Cherry_Wood: { xp: 90, image: "" },
            Spruce_Wood: { xp: 70, image: "" },
            Birch_Wood: { xp: 70, image: "" },
            Jungle_Wood: { xp: 70, image: "" },
            Acacia_Wood: { xp: 70, image: "" },
            Dark_Oak_Wood: { xp: 70, image: "" },
            Pale_Oak_Wood: { xp: 110, image: "" },
            Mangrove_Wood: { xp: 80, image: "" },
            Mangrove_Log: { xp: 95, image: "" },
            Mangrove_Roots: { xp: 10, image: "" },
            Red_Mushroom_Block: { xp: 70, image: "" },
            Brown_Mushroom_Block: { xp: 70, image: "" },
            Mushroom_Stem: { xp: 80, image: "" },
        },
    },
    excavation: {
        name: "Excavation",
        frenchName: "Fouille",
        actions: {
            Clay: { xp: 40, image: "" },
            Dirt: { xp: 40, image: "" },
            Rooted_Dirt: { xp: 60, image: "" },
            Coarse_Dirt: { xp: 40, image: "" },
            Podzol: { xp: 40, image: "" },
            Grass_Block: { xp: 40, image: "" },
            Gravel: { xp: 40, image: "" },
            Mycelium: { xp: 40, image: "" },
            Sand: { xp: 40, image: "" },
            Red_Sand: { xp: 40, image: "" },
            Snow: { xp: 20, image: "" },
            Snow_Block: { xp: 40, image: "" },
            Soul_Sand: { xp: 40, image: "" },
            Soul_Soil: { xp: 40, image: "" },
            Mud: { xp: 80, image: "" },
            Muddy_Mangrove_Roots: { xp: 90, image: "" },
        },
    },
    fishing: {
        name: "Fishing",
        frenchName: "Pêche",
        actions: {
            Cod: { xp: 100, image: "" },
            Salmon: { xp: 600, image: "" },
            Tropical_Fish: { xp: 10000, image: "" },
            Pufferfish: { xp: 2400, image: "" },
            Shake: { xp: 50, image: "assets/images/mobs/zombie.png" },
        },
    },
    herbalism: {
        name: "Herbalism",
        frenchName: "Herboristerie",
        actions: {
            Bush: { xp: 11, image: "" },
            Cactus_Flower: { xp: 60, image: "" },
            Firefly_Bush: { xp: 15, image: "" },
            Leaf_Litter: { xp: 2, image: "" },
            Short_Dry_Grass: { xp: 6, image: "" },
            Tall_Dry_Grass: { xp: 12, image: "" },
            Wildflowers: { xp: 15, image: "" },
            Open_Eyeblossom: { xp: 66, image: "" },
            Closed_Eyeblossom: { xp: 66, image: "" },
            Pitcher_Plant: { xp: 160, image: "" },
            Pink_Petals: { xp: 10, image: "" },
            Small_Dripleaf: { xp: 140, image: "" },
            Big_Dripleaf: { xp: 140, image: "" },
            Cave_Vines: { xp: 90, image: "" },
            Pale_Hanging_Moss: { xp: 150, image: "" },
            Pale_Moss_Block: { xp: 10, image: "" },
            Pale_Moss_Carpet: { xp: 10, image: "" },
            Glow_Lichen: { xp: 5, image: "" },
            Moss_Block: { xp: 150, image: "" },
            Crimson_Roots: { xp: 6, image: "" },
            Warped_Roots: { xp: 6, image: "" },
            Nether_Wart_Block: { xp: 3, image: "" },
            Warped_Wart_Block: { xp: 3, image: "" },
            Nether_Sprouts: { xp: 10, image: "" },
            Crimson_Fungus: { xp: 50, image: "" },
            Warped_Fungus: { xp: 50, image: "" },
            Shroomlight: { xp: 250, image: "" },
            Bee_Nest: { xp: 200, image: "" },
            Sweet_Berry_Bush: { xp: 50, image: "" },
            Seagrass: { xp: 10, image: "" },
            Tall_Seagrass: { xp: 10, image: "" },
            Kelp: { xp: 3, image: "" },
            Tube_Coral: { xp: 80, image: "" },
            Brain_Coral: { xp: 90, image: "" },
            Bubble_Coral: { xp: 75, image: "" },
            Fire_Coral: { xp: 120, image: "" },
            Horn_Coral: { xp: 175, image: "" },
            Tube_Coral_Fan: { xp: 80, image: "" },
            Brain_Coral_Fan: { xp: 90, image: "" },
            Bubble_Coral_Fan: { xp: 75, image: "" },
            Fire_Coral_Fan: { xp: 120, image: "" },
            Horn_Coral_Fan: { xp: 175, image: "" },
            Dead_Tube_Coral: { xp: 10, image: "" },
            Dead_Brain_Coral: { xp: 10, image: "" },
            Dead_Bubble_Coral: { xp: 10, image: "" },
            Dead_Fire_Coral: { xp: 10, image: "" },
            Dead_Horn_Coral: { xp: 10, image: "" },
            Dead_Tube_Coral_Fan: { xp: 10, image: "" },
            Dead_Brain_Coral_Fan: { xp: 10, image: "" },
            Dead_Bubble_Coral_Fan: { xp: 10, image: "" },
            Dead_Fire_Coral_Fan: { xp: 10, image: "" },
            Dead_Horn_Coral_Fan: { xp: 10, image: "" },
            Allium: { xp: 300, image: "" },
            Azure_Bluet: { xp: 150, image: "" },
            Blue_Orchid: { xp: 150, image: "" },
            Brown_Mushroom: { xp: 150, image: "" },
            Cactus: { xp: 30, image: "" },
            Chorus_Flower: { xp: 25, image: "" },
            Chorus_Plant: { xp: 1, image: "" },
            Carrot: { xp: 50, image: "" },
            Cocoa: { xp: 30, image: "" },
            Potato: { xp: 50, image: "" },
            Wheat: { xp: 50, image: "" },
            Beetroot: { xp: 50, image: "" },
            Nether_Wart: { xp: 50, image: "" },
            Dead_Bush: { xp: 30, image: "" },
            Lilac: { xp: 50, image: "" },
            Melon: { xp: 20, image: "" },
            Orange_Tulip: { xp: 150, image: "" },
            Oxeye_Daisy: { xp: 150, image: "" },
            Peony: { xp: 50, image: "" },
            Pink_Tulip: { xp: 150, image: "" },
            Poppy: { xp: 100, image: "" },
            Pumpkin: { xp: 20, image: "" },
            Red_Mushroom: { xp: 150, image: "" },
            Red_Tulip: { xp: 150, image: "" },
            Rose_Bush: { xp: 50, image: "" },
            Fern: { xp: 10, image: "" },
            Grass: { xp: 10, image: "" },
            Short_Grass: { xp: 10, image: "" },
            Sugar_Cane: { xp: 30, image: "" },
            Sunflower: { xp: 50, image: "" },
            Tall_Grass: { xp: 50, image: "" },
            Large_Fern: { xp: 50, image: "" },
            Vine: { xp: 10, image: "" },
            Weeping_Vines_Plant: { xp: 10, image: "" },
            Twisting_Vines_Plant: { xp: 10, image: "" },
            Lily_Pad: { xp: 100, image: "" },
            White_Tulip: { xp: 150, image: "" },
            Dandelion: { xp: 100, image: "" },
            Bamboo: { xp: 10, image: "" },
            Cornflower: { xp: 150, image: "" },
            Lily_Of_The_Valley: { xp: 150, image: "" },
            Wither_Rose: { xp: 500, image: "" },
            Torchflower: { xp: 90, image: "" },
        },
    },
    unarmed: {
        name: "Unarmed",
        frenchName: "Poing",
        actions: {
            // TODO : Understand how combat works in MCMMO
        },
    },
    swords: {
        name: "Swords",
        frenchName: "Épées",
        actions: {
            // TODO : Understand how combat works in MCMMO
        },
    },
    axes: {
        name: "Axes",
        frenchName: "Haches",
        actions: {
            // TODO : Understand how combat works in MCMMO
        },
    },
    archery: {
        name: "Archery",
        frenchName: "Archerie",
        actions: {
            // TODO : Understand how combat works in MCMMO
        },
    },
    taming: {
        name: "Taming",
        frenchName: "Apprivoisement",
        actions: {
            Camel: { xp: 1300, image: "" },
            Sniffer: { xp: 1500, image: "" },
            Snifflet: { xp: 900, image: "" },
            Llama: { xp: 1200, image: "" },
            Wolf: { xp: 250, image: "" },
            Ocelot: { xp: 500, image: "" },
            Horse: { xp: 1000, image: "" },
            Donkey: { xp: 1000, image: "" },
            Mule: { xp: 1000, image: "" },
            Skeleton_Horse: { xp: 1000, image: "" },
            Zombie_Horse: { xp: 1000, image: "" },
            Parrot: { xp: 1100, image: "" },
            Cat: { xp: 500, image: "" },
            Fox: { xp: 1000, image: "" },
            Panda: { xp: 1000, image: "" },
            Bee: { xp: 100, image: "" },
            Goat: { xp: 250, image: "" },
            Axolotl: { xp: 600, image: "" },
            Frog: { xp: 900, image: "" },
        },
    },
    repair: {
        name: "Repair",
        frenchName: "Réparation",
        actions: {
            //I think repair don't work in MCMMO - Valderion
        },
    },
    acrobatics: {
        name: "Acrobatics",
        frenchName: "Acrobatie",
        actions: {
            // (b-3)*120 xp and *2 if feather falling boots
        },
    },
    alchemy: {
        name: "Alchemy",
        frenchName: "Alchimie",
        actions: {
            // TODO : Understand how alchemy works in MCMMO
        },
    },
    maces: {
        name: "Maces",
        frenchName: "Maces",
        actions: {
            // TODO : Understand how combat works in MCMMO
        },
    },
    trident: {
        name: "Trident",
        frenchName: "Trident",
        actions: {
            // TODO : Understand how combat works in MCMMO
        },
    },
    crossbows: {
        name: "Crossbows",
        frenchName: "Arbalètes",
        actions: {
            // TODO : Understand how combat works in MCMMO
        },
    },
};
